const generate_quote = document.getElementById("quote_text");

const generateButton = document.getElementById("generate-button");
const imageContainer = document.getElementById("image-container");
const generatedImage = document.getElementById("generated-image");
const downloadButton = document.getElementById("download-button");

let random_quotes = [
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "The future depends on what you do today. - Mahatma Gandhi",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "The secret of getting ahead is getting started. - Mark Twain",
  "It always seems impossible until it's done. - Nelson Mandela",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
  "The harder you work for something, the greater you'll feel when you achieve it. - Unknown",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "The best way to predict the future is to create it. - Peter Drucker",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh (Alice in Wonderland)",
  "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
  "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
  "The harder you work for something, the greater you'll feel when you achieve it. - Unknown",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
  "Opportunities don't happen. You create them. - Chris Grosser",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
  "The only thing standing between you and your dream is the will to try and the belief that it is actually possible. - Joel Brown",
  "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
  "Opportunities don't happen. You create them. - Chris Grosser",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "The harder the conflict, the greater the triumph. - George Washington",
  "You learn more from failure than from success. Don't let it stop you. Failure builds character. - Unknown",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh (Alice in Wonderland)",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "The future depends on what you do today. - Mahatma Gandhi",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "The secret of getting ahead is getting started. - Mark Twain",
  "It always seems impossible until it's done. - Nelson Mandela",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "The future depends on what you do today. - Mahatma Gandhi",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "The secret of getting ahead is getting started. - Mark Twain",
  "It always seems impossible until it's done. - Nelson Mandela",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
  "The harder you work for something, the greater you'll feel when you achieve it. - Unknown",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
  "Opportunities don't happen. You create them. - Chris Grosser",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Success is not just about making money. It's about making a difference. - Unknown",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh (Alice in Wonderland)",
  "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful. - Joshua J. Marine",
  "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
  "Success is not the absence of failure; it's the persistence through failure. - Aisha Tyler",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. - Chantal Sutherland",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "The harder the conflict, the greater the triumph. - George Washington",
  "You learn more from failure than from success. Don't let it stop you. Failure builds character. - Unknown",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "The future depends on what you do today. - Mahatma Gandhi",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh (Alice in Wonderland)",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "The harder the conflict, the greater the triumph. - George Washington",
  "You learn more from failure than from success. Don't let it stop you. Failure builds character. - Unknown",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "The future depends on what you do today. - Mahatma Gandhi",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "The secret of getting ahead is getting started. - Mark Twain",
  "It always seems impossible until it's done. - Nelson Mandela",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
  "Opportunities don't happen. You create them. - Chris Grosser",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Success is not just about making money. It's about making a difference. - Unknown",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh (Alice in Wonderland)",
  "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful. - Joshua J. Marine",
  "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
  "Success is not the absence of failure; it's the persistence through failure. - Aisha Tyler",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "The harder the conflict, the greater the triumph. - George Washington",
  "You learn more from failure than from success. Don't let it stop you. Failure builds character. - Unknown",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "The future depends on what you do today. - Mahatma Gandhi",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh (Alice in Wonderland)",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "The harder the conflict, the greater the triumph. - George Washington",
  "You learn more from failure than from success. Don't let it stop you. Failure builds character. - Unknown",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "The future depends on what you do today. - Mahatma Gandhi",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "The secret of getting ahead is getting started. - Mark Twain",
  "It always seems impossible until it's done. - Nelson Mandela",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
  "Opportunities don't happen. You create them. - Chris Grosser",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Success is not just about making money. It's about making a difference. - Unknown",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh (Alice in Wonderland)",
  "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful. - Joshua J. Marine",
  "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
  "Success is not the absence of failure; it's the persistence through failure. - Aisha Tyler",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "The harder the conflict, the greater the triumph. - George Washington",
  "You learn more from failure than from success. Don't let it stop you. Failure builds character. - Unknown",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "The future depends on what you do today. - Mahatma Gandhi",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh (Alice in Wonderland)",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "The harder the conflict, the greater the triumph. - George Washington",
  "You learn more from failure than from success. Don't let it stop you. Failure builds character. - Unknown",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "The future depends on what you do today. - Mahatma Gandhi",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "The secret of getting ahead is getting started. - Mark Twain",
  "It always seems impossible until it's done. - Nelson Mandela",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
  "Opportunities don't happen. You create them. - Chris Grosser",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Success is not just about making money. It's about making a difference. - Unknown",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh (Alice in Wonderland)",
  "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful. - Joshua J. Marine",
  "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
  "Success is not the absence of failure; it's the persistence through failure. - Aisha Tyler",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "The harder the conflict, the greater the triumph. - George Washington",
  "You learn more from failure than from success. Don't let it stop you. Failure builds character. - Unknown",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "The future depends on what you do today. - Mahatma Gandhi",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh (Alice in Wonderland)",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "The harder the conflict, the greater the triumph. - George Washington",
  "You learn more from failure than from success. Don't let it stop you. Failure builds character. - Unknown",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "The future depends on what you do today. - Mahatma Gandhi",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "The secret of getting ahead is getting started. - Mark Twain",
  "It always seems impossible until it's done. - Nelson Mandela",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
  "Opportunities don't happen. You create them. - Chris Grosser",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Success is not just about making money. It's about making a difference. - Unknown",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh (Alice in Wonderland)",
  "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful. - Joshua J. Marine",
  "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
  "Success is not the absence of failure; it's the persistence through failure. - Aisha Tyler",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "The harder the conflict, the greater the triumph. - George Washington",
  "You learn more from failure than from success. Don't let it stop you. Failure builds character. - Unknown",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "The future depends on what you do today. - Mahatma Gandhi",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh (Alice in Wonderland)",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "The harder the conflict, the greater the triumph. - George Washington",
  "You learn more from failure than from success. Don't let it stop you. Failure builds character. - Unknown",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "The future depends on what you do today. - Mahatma Gandhi",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "The secret of getting ahead is getting started. - Mark Twain",
  "It always seems impossible until it's done. - Nelson Mandela",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
  "Opportunities don't happen. You create them. - Chris Grosser",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Success is not just about making money. It's about making a difference. - Unknown",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh (Alice in Wonderland)",
  "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful. - Joshua J. Marine",
  "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
  "Success is not the absence of failure; it's the persistence through failure. - Aisha Tyler",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "The harder the conflict, the greater the triumph. - George Washington",
  "You learn more from failure than from success. Don't let it stop you. Failure builds character. - Unknown",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "The future depends on what you do today. - Mahatma Gandhi",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh (Alice in Wonderland)",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "The harder the conflict, the greater the triumph. - George Washington",
  "You learn more from failure than from success. Don't let it stop you. Failure builds character. - Unknown",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "The future depends on what you do today. - Mahatma Gandhi",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "The secret of getting ahead is getting started. - Mark Twain",
  "It always seems impossible until it's done. - Nelson Mandela",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
  "Opportunities don't happen. You create them. - Chris Grosser",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Success is not just about making money. It's about making a difference. - Unknown",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh (Alice in Wonderland)",
  "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful. - Joshua J. Marine",
  "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
  "Success is not the absence of failure; it's the persistence through failure. - Aisha Tyler",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "The harder the conflict, the greater the triumph. - George Washington",
  "You learn more from failure than from success. Don't let it stop you. Failure builds character. - Unknown",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "The future depends on what you do today. - Mahatma Gandhi",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh (Alice in Wonderland)",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "The harder the conflict, the greater the triumph. - George Washington",
  "You learn more from failure than from success. Don't let it stop you. Failure builds character. - Unknown",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "The future depends on what you do today. - Mahatma Gandhi",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "The secret of getting ahead is getting started. - Mark Twain",
  "It always seems impossible until it's done. - Nelson Mandela",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
  "Opportunities don't happen. You create them. - Chris Grosser",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Success is not just about making money. It's about making a difference. - Unknown",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh (Alice in Wonderland)",
  "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful. - Joshua J. Marine",
  "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
  "Success is not the absence of failure; it's the persistence through failure. - Aisha Tyler",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "The harder the conflict, the greater the triumph. - George Washington",
  "You learn more from failure than from success. Don't let it stop you. Failure builds character. - Unknown",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "The future depends on what you do today. - Mahatma Gandhi",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh (Alice in Wonderland)",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Strive for progress, not perfection. - Unknown",
  "Your time is limited, so don't waste it living someone else's life. - Steve Jobs",
  "Success is not the destination, but the journey. - Zig Ziglar",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Dream big and dare to fail. - Norman Vaughan",
  "The only thing that stands between you and your dream is the will to try and the belief that it is actually possible. - Joel Brown",
  "The only thing we have to fear is fear itself. - Franklin D. Roosevelt",
  "In the middle of every difficulty lies opportunity. - Albert Einstein",
  "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
  "Don't wait. The time will never be just right. - Napoleon Hill",
  "The future depends on what you do today. - Mahatma Gandhi",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
  "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got this. - Chantal Sutherland",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "The harder you work for something, the greater you'll feel when you achieve it. - Unknown",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
  "You miss 100% of the shots you don't take. - Wayne Gretzky",
  "The biggest risk is not taking any risk. In a world that is changing quickly, the only strategy that is guaranteed to fail is not taking risks. - Mark Zuckerberg",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
  "Success is not just about making money. It's about making a difference. - Unknown",
  "If you can dream it, you can do it. - Walt Disney",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "Success is not the absence of failure; it's the persistence through failure. - Aisha Tyler",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "The harder the conflict, the greater the triumph. - George Washington",
  "You learn more from failure than from success. Don't let it stop you. Failure builds character. - Unknown",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh (Alice in Wonderland)",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful. - Joshua J. Marine",
  "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
  "Opportunities don't happen. You create them. - Chris Grosser",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
  "The secret of getting ahead is getting started. - Mark Twain",
  "It always seems impossible until it's done. - Nelson Mandela",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "Life is either a daring adventure or nothing at all. - Helen Keller",
  "The only thing standing between you and your dream is the will to try and the belief that it is actually possible. - Joel Brown",
  "In the midst of chaos, there is also opportunity. - Sun Tzu",
  "Your life does not get better by chance, it gets better by change. - Jim Rohn",
  "The journey of a thousand miles begins with one step. - Lao Tzu",
  "The only way to predict the future is to create it. - Peter Drucker",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Success is not just about making money. It's about making a difference. - Unknown",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh (Alice in Wonderland)",
  "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful. - Joshua J. Marine",
  "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
  "Success is not the absence of failure; it's the persistence through failure. - Aisha Tyler",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "The harder the conflict, the greater the triumph. - George Washington",
  "You learn more from failure than from success. Don't let it stop you. Failure builds character. - Unknown",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "The future depends on what you do today. - Mahatma Gandhi",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh (Alice in Wonderland)",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
];

function show_quote() {
  quotes = random_quotes[Math.floor(Math.random() * random_quotes.length)];
  generate_quote.innerHTML = `${quotes}`;
}

downloadButton.addEventListener("click", () => {
  const text = `${quotes}`;
  const canvas = document.createElement("canvas");
  const context = canvas.getContext("2d");

  canvas.width = 1920;
  canvas.height = 1080;

  context.fillStyle = "#000";
  context.fillRect(0, 0, canvas.width, canvas.height);

  context.font = '2.5rem "Times New Roman", serif';
  context.fillStyle = "#fff";
  context.textAlign = "center";
  context.textBaseline = "middle";

  const x = canvas.width / 2;
  const y = canvas.height / 2;

  context.fillText(text, x, y);

  generatedImage.src = canvas.toDataURL("image/png");
  downloadImage();
});

function downloadImage() {
  const link = document.createElement("a");
  link.href = generatedImage.src;
  link.download = "quote.png";
  link.click();
}
